spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  jackson:
    property-naming-strategy: SNAKE_CASE

  profiles:
    include: oauth2
    active: local

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secreteKey: ABCDEFG
  expire-length: 600000
